resolvers ++= Resolver.sonatypeOssRepos("releases")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"   % "2.5.1")
addSbtPlugin("com.dwijnand"    % "sbt-dynver"     % "4.1.1")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix" % "0.10.4")
addSbtPlugin("com.github.sbt"  % "sbt-ci-release" % "1.5.12")
